### ISSUE TITLE
PHP MySQL Extension not detected

### ISSUE THREAD

**Issue by stickyfin** [Chewbaka69/PlexShare#10]
When checking configuration, the config didn't detect PHP MySQL Extension. The php_mysql is installed.

OS: Ubuntu 20.04
PHP version: 7.4

Screenshot from /install:
![image](https://user-images.githubusercontent.com/38528050/118310685-88498580-b521-11eb-82b7-6d04b010558b.png)

Screenshot from info.php:
![image](https://user-images.githubusercontent.com/38528050/118310848-b3cc7000-b521-11eb-8d2f-c2c7710000d4.png)
![image](https://user-images.githubusercontent.com/38528050/118310913-c9419a00-b521-11eb-8fd7-c1bc144265b6.png)

When I proceed to the table creation, it stuck on "Please wait we are creating your tables!"

When I checked log file located in /var/www/plexshare/fuel/app/logs/2021/05, the following ERROR appeared multiple times:

ERROR - 2021-05-15 02:10:01 --> 0 - invalid data source name in /var/www/plexshare/fuel/core/classes/database/pdo/connection.php on line 86
ERROR - 2021-05-15 02:10:01 --> 0 - invalid data source name in /var/www/plexshare/fuel/core/classes/database/pdo/connection.php on line 512
ERROR - 2021-05-15 02:20:01 --> 2 - Invalid argument supplied for foreach() in /var/www/plexshare/fuel/app/tasks/server.php on line 22
ERROR - 2021-05-15 02:20:01 --> 2 - Invalid argument supplied for foreach() in /var/www/plexshare/fuel/app/tasks/server.php on line 189

In addition, I tried to complete the setup, but encounter with the following error when trying to setup Server config:
![image](https://user-images.githubusercontent.com/38528050/118315045-926e8280-b527-11eb-9629-0c0383f257b8.png)

**Comment by Chewbaka69** [comment]
Oh ok thanks, i'll take a look on it asap

**Comment by Chewbaka69** [comment]
You can try to reinstall the app :)

**Comment by stickyfin** [comment]
I have reinstall the app, and it can detect the PHP Extension MySQL. 

However, it stuck at table creation process:
![image](https://user-images.githubusercontent.com/38528050/118917328-2e9eec00-b963-11eb-953d-3db89ac75c11.png)

I checked the db and can confirm that the tables created:
![image](https://user-images.githubusercontent.com/38528050/118917428-7291f100-b963-11eb-8759-d864a5154555.png)

From logs, the following appeared:
_ERROR - 2021-05-20 12:00:01 --> 2 - Invalid argument supplied for foreach() in /var/www/plexshare/fuel/app/tasks/server.php on line 189
ERROR - 2021-05-20 12:00:01 --> 2 - Invalid argument supplied for foreach() in /var/www/plexshare/fuel/app/tasks/server.php on line 22_

If I proceed to the next step, I will encounter like the following:
![image](https://user-images.githubusercontent.com/38528050/118315045-926e8280-b527-11eb-9629-0c0383f257b8.png)

Thank you!

**Comment by Chewbaka69** [comment]
the log and the orther error page are nomal, it is because we dont have finish the installation.
So i reproduce the bug and i have a pop-up with an error that appear quickly with this error on the network:
{"error":true,"message":"SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails with query: \u0022DROP TABLE IF EXISTS plex_permission\u0022"}

I work on it to fix it

**Comment by Chewbaka69** [comment]
I have push some fixes, can you try to reinstall it :)

**Comment by stickyfin** [comment]
I will test it now. 

How long does usually it takes to create all those required tables?

**Comment by stickyfin** [comment]
Okay now I can proceed to add the plex server.

However I encountered with the following:
![image](https://user-images.githubusercontent.com/38528050/118960725-2ad88d00-b996-11eb-8bb1-c3f8a14b5eb1.png)

Is there any steps I missed?

**Comment by Chewbaka69** [comment]
fixed

**Comment by stickyfin** [comment]
Now seems able to finish the setup and proceed to the login page.

Now I stuck with this right after insert username and password:
![image](https://user-images.githubusercontent.com/38528050/118977959-54e77a80-b9a9-11eb-944b-d459b7b90405.png)

**Comment by Chewbaka69** [comment]
you can retry and sorry for bugs

**Comment by Chewbaka69** [comment]
all work fine?
