### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by xiNeRoar** [Chewbaka69/PlexShare#11]
Will this repo repack in docker to release for easier maintenance and installation?

**Comment by Chewbaka69** [comment]
Yes this repo will include a docker installation ;)

**Comment by xiNeRoar** [comment]
dose the docker installation available now?

**Comment by Chewbaka69** [comment]
No now, i'll do the docker installation asap with the documentation

**Comment by Brramble** [comment]
Hi @Chewbaka69 just wanted to see if there was any update on the docker support? Cheers

**Comment by Chewbaka69** [comment]
Actually not mutch time to finish it, but i have already started the docker part :)

**Comment by LubricantJam** [comment]
@Chewbaka69 Where can this be found?

**Comment by Chewbaka69** [comment]
I will add the link on the readme and in the wiki
