### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by JigSawFr** [Chewbaka69/PlexShare#15]
Hi there,
Can you consider deploying docker images to Github and/or Dockerhub ?
Thanks you

LinkedTo: https://github.com/saltyorg/Sandbox/issues/91

**Comment by Chewbaka69** [comment]
Hello,
Yes sure, I will implement a CI when I have time ;)

**Comment by Chewbaka69** [comment]
@JigSawFr Re,

I have added the CI, and i have pushed the pre-alpha version of PlexShare on DockerHub.

The docker-compose.yml use this image.
And the docker-compose.dev.yaml use a local build to dev on it.

Image link: [https://hub.docker.com/r/chewbaka/plexshare](https://hub.docker.com/r/chewbaka/plexshare)

😀

**Comment by JigSawFr** [comment]
@Chewbaka69 great ! Thank you too for this addition :)
