### ISSUE TITLE
Install Process (Docker) - Invalid basepath when saving MySQL data

### ISSUE THREAD

**Issue by JigSawFr** [Chewbaka69/PlexShare#16]
Hi there,

**Describe the bug**
Unable to save database settings due to an error.

**To Reproduce**
1. Go to http://localhost/install#SQL
2. Fill info (or not)
3. Click on save

**400 Bad Request from http://localhost/rest/install/config.json**
`{"error":true,"message":"Invalid basepath: \u0022\/app\/fuel\/core\/config\/\u0022, cannot update a file at this location."}`

Filling example:

```
host: 
127.0.0.1
port: 
63897
database: 
plexshare
prefix: 
pshare_
username: 
root
password: 
password123
```

**Expected behavior**
Next step or more precise error.

**Screenshots**
![image](https://user-images.githubusercontent.com/5781907/201165999-114dea3d-6301-40a1-8ee6-5e65d9d09e78.png)

Tried on Docker with Linux/Windows, with docker compose.

**Comment by Chewbaka69** [comment]
A file was missing.
I commit the missing file, and update the docker image

**Comment by JigSawFr** [comment]
@Chewbaka69 thanks

**Comment by Chewbaka69** [comment]
If all is good, you will can close this issue 😀
