### ISSUE TITLE
Install Process (Docker) - Wrong permission for app o/

### ISSUE THREAD

**Issue by JigSawFr** [Chewbaka69/PlexShare#17]
Hey @Chewbaka69 thank you again for your recent edits,
As I've seen, you copy your app directory in the image,
⚠️ But it's done as root and the **user of docker image is application (1000:1000)**
Cf. https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html#webdevops-php-nginx

So we are still unable to save mysql config file with error:
`{"error":true,"message":"No write access to: \u0022\/app\/fuel\/app\/config\/\u0022, cannot update a file."}`

Solution:
Add `USER` instruction to Dockerfile to switch to "application" user/group (UID: 1000 / GUID:1000)
Cf. https://www.geeksforgeeks.org/docker-user-instruction/

or add a `RUN chown -vR 1000:1000 /app/fuel/app` at end

Workaround:
`docker exec plexshare /bin/bash -c 'chown -vR 1000:1000 /app/fuel/app'`

Thanks :)

**Comment by Chewbaka69** [comment]
Thanks for all bugs that you find, i'll fix it asap

**Comment by Chewbaka69** [comment]
Fixed, image is currently in building

**Comment by JigSawFr** [comment]
@Chewbaka69 no problem !
If you want to discuss you can reach us on discord: https://discord.gg/FgrGzU95
Thanks for your fix !
