### ISSUE TITLE
Cannot declare class Fuel\Migrations\Create_user_download, because the name is already in use

### ISSUE THREAD

**Issue by JigSawFr** [Chewbaka69/PlexShare#19]
At MySQL tables creation step, I'm encountering this error:

```
ErrorException [ Compile Error ]:
Cannot declare class Fuel\Migrations\Create_user_download, because the name is already in use
```

![image](https://user-images.githubusercontent.com/5781907/201234078-7d590a0e-9860-4db0-a119-2a324f040c94.png)

Thanks for your help :)

**Comment by Chewbaka69** [comment]
Fixed on the last commit.

docker image updated.

Thanks a lot 😀

**Comment by JigSawFr** [comment]
Works too ! Thank you
