### ISSUE TITLE
Bug: User/Pass incorrect

### ISSUE THREAD

**Issue by JigSawFr** [Chewbaka69/PlexShare#22]
Hi,
Seems strange, even if install runs fine, user/password is incorrect at login page after that.
Tried also with simple duo like admin/test, but no luck.
Maybe a problem somewhere ?

Nothing relevant in logs, nothing in browser console nor docker logs.
![image](https://user-images.githubusercontent.com/5781907/201351490-37603576-45fb-4284-a495-964615a9efb6.png)

**Comment by Chewbaka69** [comment]
I was in weekend, I'll take a look asap

**Comment by Chewbaka69** [comment]
Fixed with last commit
Image update

**Comment by JigSawFr** [comment]
All good it's working now as expected ;)
Thanks !
