### ISSUE TITLE
Launch creation table error

### ISSUE THREAD

**Issue by Nexius2** [Chewbaka69/PlexShare#23]
got a message "SQLSTATE[HY000] [2002] No such file or directory" when trying to create tables.
in the logs, I found this "SQLSTATE[HY000] [2002] No such file or directory in /app/fuel/core/classes/database/pdo/connection.php on line 86" couldn't find that file...
db is created but it looks like it can't find it

thanks

![Capture d’écran 2022-11-24 130013](https://user-images.githubusercontent.com/9554635/203779456-f95fcb13-e441-4bbf-8e9a-167ba086041a.jpg)
![Capture d’écran 2022-11-24 130059](https://user-images.githubusercontent.com/9554635/203779616-4430e365-44bb-48d4-9b68-2355f820dc27.jpg)

**Comment by Chewbaka69** [comment]
This error is related to the previous step on the installer.
Confirmation SQL, this step create the config file to connect to the db and this file is missing.

**Comment by Nexius2** [comment]
did  I miss something? I'd like to make it work and have a look at the app as I was making my own app to do the same thing :-)
thanks

**Comment by Chewbaka69** [comment]
Did you click before that step on the  "Configuration SQL" on the left side and click on the save button, after completing all the fields?

**Comment by Nexius2** [comment]
tryied it again and it worked. thanks, I'll try it ;-)
