### ISSUE TITLE
Docker installation, nginx 403 Forbidden

### ISSUE THREAD

**Issue by kosowarisuppe** [Chewbaka69/PlexShare#24]
Installed plexshare on Unraid 6.12.6

![image](https://github.com/Chewbaka69/PlexShare/assets/46192786/78ff1504-d80d-495a-b871-8acaff6acf87)

when I try to open the page I'll get 403 Forbidden
![image](https://github.com/Chewbaka69/PlexShare/assets/46192786/4775aa5a-8ffc-4e0e-a12b-e7998c32c60b)

**Comment by Chewbaka69** [comment]
this is a a strange issue, can you give me the log error please?

**Comment by kosowarisuppe** [comment]
where is it stored?

**Comment by Chewbaka69** [comment]
You need to build it
