### ISSUE TITLE
Depoyment

### ISSUE THREAD

**Issue by glover279** [Chewbaka69/PlexShare#3]
Could I get some help deploying this? Where is the config located? This looks amazing!

**Comment by Chewbaka69** [comment]
This is an alpha a this time, I write some information to install it when I finish this alpha.

At this to install it, you only need copy the source code to your www and configure your Apache or nginx to fuelphp.
After go to:
http://yourwebsite.com/install

**Comment by julientaverne** [comment]
Hi, great news !
But i don't find install.php file.
Can you please tell me where is it ? Or explain me how fuelphp works ?
Thank you in advance.
Best regards, Julien.

**Comment by Chewbaka69** [comment]
@glover279 the config file are store in fuel/app/config
But files don't exist before installation

**Comment by julientaverne** [comment]
Hi, can you please help me telling how i have to configure my Apache ?
Thank you in adavance,
Best regards, Julien

**Comment by Chewbaka69** [comment]
Hi,
You can go to the wiki page of the project, I have write some information about the installation.

Best regards,
