### ISSUE TITLE
Fuel\Core\PhpErrorException [ Notice ]: Undefined index: hash

### ISSUE THREAD

**Issue by glover279** [Chewbaka69/PlexShare#5]
**Describe the bug**
After install going to login presents Fuel\Core\PhpErrorException [ Notice ]:
Undefined index: hash
**To Reproduce**
1. Install the application'
2. Go to login page

**Expected behavior**
Website loads properly

**Screenshots**
![image](https://user-images.githubusercontent.com/11718932/49082235-f286e680-f251-11e8-832d-947772fa1ed4.png)

**Comment by Chewbaka69** [comment]
Remove the file **lock.php** in **fuel/app/config**
And after go to this URL
http://yourwebsite.com/install
Because on this url you have to configure some information

**Comment by glover279** [comment]
Unfortunately I still get the same error

**Comment by Chewbaka69** [comment]
On the url /install, your are missing some parameters.
So go to the file fuel/app/config/db.php and add a line with the port you use to connect to your DB, just under the host.

**Comment by Chewbaka69** [comment]
Reclone the repo with the last update

**Comment by Chewbaka69** [comment]
Any other problems?

**Comment by glover279** [comment]
Yeah there seem to be problems creating the tables. I got them to create
once and then it didnt create the plex_user table

**Comment by Chewbaka69** [comment]
On your website there is this error writen when i create tables:
SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

So i think the user used to connect to the database is wrong or having not rights

**Comment by glover279** [comment]
Sorry for the late response. I will give it another shot

**Comment by Chewbaka69** [comment]
Do you have an other problem?
