### ISSUE TITLE
Does anyone know how to get this running?

### ISSUE THREAD

**Issue by hamflix** [Chewbaka69/PlexShare#6]
Hello,

I've followed the WIKI step by step for an NGINX setup.

When I visited my web address I only receive 502 Bad Gateway.

Please help!

**Comment by Chewbaka69** [comment]
Ok can you post your Nginx error.log please.

**Comment by hamflix** [comment]
`2019/07/29 14:58:22 [error] 3513#3513: *7 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.xxx.xxx.xx, server: example.example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "example.example.com"`

I changed the server name and IP address of client.

**Comment by Chewbaka69** [comment]
Ok so all is good now?

**Comment by Chewbaka69** [comment]
Did you have installed php-fpm?
Because i use it.

**Comment by hamflix** [comment]
Hello, Yes I have php-fpm installed.

**Comment by Chewbaka69** [comment]
Did you have tried this:
https://serverfault.com/a/617793

**Comment by hamflix** [comment]
Just completed that; we're definitely making progress, now i'm receiving this:

`No composer autoloader found. Please run composer to install the FuelPHP framework dependencies first!`

**Comment by Chewbaka69** [comment]
Go to plexshare, and try `php composer.phar update`

**Comment by hamflix** [comment]
I literally just followed your Wiki steps.

`cd /var/www/`
`git clone https://github.com/Chewbaka69/PlexShare.git plexshare`

then configured my NGINX server block: 

```
server {
    server_name mydomain.com; # replace by your domain name here

    # make sure Nginx can write to these files
    access_log /var/log/nginx/plexshare_access.log;
    error_log /var/log/nginx/plexshare_error.log;
    root /var/www/plexshare/public;
    # This is the default configuration that you can adapt it to your installation

    location / {
        index index.php;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param FUEL_ENV "production";
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
```

Then I changed `fastcgi_pass 127.0.0.1:9000;` to `fastcgi_pass unix:/var/run/php5-fpm.sock;` like you recommended.

**Comment by hamflix** [comment]
I have just tried your suggestion above and that resolved the composer issue, but now i'm receiving:

`Oops! An unexpected error has occurred.`

**Comment by hamflix** [comment]
![image](https://user-images.githubusercontent.com/46073333/62312869-4e4ae480-b45d-11e9-94d6-7f193882353a.png)

**Comment by PixiBixi** [comment]
Take a look at your nginx logs and rights on directories

**Comment by Chewbaka69** [comment]
To view more details on error change this, in your Nginx conf:
`fastcgi_param FUEL_ENV "production";`
to
`fastcgi_param FUEL_ENV "development";`

And add a new screen of the error plz

**Comment by hamflix** [comment]
@PixiBixi NGINX logs show no errors, directories are all set to www:data.

@Chewbaka69 after trying this, I received the follow page error:

![image](https://user-images.githubusercontent.com/46073333/62384723-2a50d700-b521-11e9-86bc-a433058863ba.png)

plexshare_error.log is not throwing any errors.

**Comment by Chewbaka69** [comment]
What is the version of your PHP?

**Comment by hamflix** [comment]
Hey Sorry for the delay, I got a little busy. PHP Version is PHP 7.2.19

**Comment by Chewbaka69** [comment]
Can you try to downgrade the PHP version, maybe it is FuelPHP that is not compatible with PHP 7.2

**Comment by Chewbaka69** [comment]
Hey,
i have updated the install Wiki, and i have try it to a new install on my server and i have no error.
I use PHP 7.3.7 :/

Maybe retry to install

**Comment by Chewbaka69** [comment]
I have a miss configuration and i use actually PHP5.6, i have try on PHP7.3 and i have the same error

**Comment by Chewbaka69** [comment]
To fix it you need to upgrade fuel/core so update your composer.json with that:
```{
    "name": "fuel/fuel",
    "type": "project",
    "description" : "FuelPHP is a simple, flexible, community driven PHP 5.3.3+ framework, based on the best ideas of other frameworks, with a fresh start!",
    "keywords": ["application", "website", "development", "framework", "PHP", "PHP7"],
    "license": "MIT",
    "require": {
        "php": ">=5.6.33",
        "composer/installers": "~1.0",
        "fuel/core": "dev-1.9/develop",
        "fuel/auth": "1.8.*",
        "fuel/email": "1.8.*",
        "fuel/oil": "1.8.*",
        "fuel/orm": "1.8.*",
        "fuel/parser": "1.8.*",
        "fuelphp/upload": "2.0.6",
        "monolog/monolog": "^1.18",
        "phpseclib/phpseclib": "2.0.0",
        "michelf/php-markdown": "1.7.0"
    },
    "require-dev": {
        "fuel/docs": "1.8.*"
    },
    "suggest": {
        "dwoo/dwoo" : "Allow Dwoo templating with the Parser package",
        "mustache/mustache": "Allow Mustache templating with the Parser package",
        "smarty/smarty": "Allow Smarty templating with the Parser package",
        "twig/twig": "Allow Twig templating with the Parser package",
        "pyrocms/lex": "Allow Lex templating with the Parser package",
        "mthaml/mthaml": "Allow Haml templating with Twig supports with the Parser package"
    },
    "config": {
        "vendor-dir": "fuel/vendor"
    },
    "extra": {
        "installer-paths": {
            "fuel/{$name}": ["fuel/core"],
            "{$name}": ["fuel/docs"]
        }
    },
    "scripts": {
        "post-install-cmd": [
            "php oil r install"
        ]
    },
    "minimum-stability": "stable"
}
```

After this run `php composer.phar update`

**Comment by hamflix** [comment]
Awesome guys, looks like this resolved it! It might be worth rewriting the WIKI to include these steps or upgrading the repo so that it works with the latest PHP versions.

**Comment by hamflix** [comment]
Thanks again!

**Comment by Chewbaka69** [comment]
I have already upgrading the repo and update the WIKI ;)

**Comment by Chewbaka69** [comment]
Do a git pull, because the login is broken. And i have fix it.
