### ISSUE TITLE
Is this project dead? I can't seem to get it to work and need help

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Chewbaka69/PlexShare#8]
*Dont Forget to set your ENVIRONMENT variable to DEVELOPMENT*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Chewbaka69** [comment]
It's not dead but I have less time to work on it.
I will rework on it.

**Comment by cookie-monster-bit** [comment]
Yeah, i'm getting a red exclamation mark on "PHP Extension MYSQL" and the SQL database gives me errors. Any way to solve this? Seems like you need to use an old version of php has Extension MYSQL does not work on V7.

**Comment by Chewbaka69** [comment]
Hello,
I am on PHP 7.4
Have you install php-pdo?
And if you don't show the error I can't help you.
